server:
  port: 80

spring:
  profiles:
    active: prop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

client:
  clientId: 5ffc31b3d3ef472faaa23ed35081a998
  clientSecret: 940114100d31bff5ab16b4bbb19ec2ad89b78693
  pid: "35772384_257791152"
  uid: 7777
  rate: 0.45

taobao:
  url: https://eco.taobao.com/router/rest
  appKey: 34166008
  appSecret: 505774d570ac6116cfca3f1f94cc7d5c
  xpid: mm_3596038134_2774850102_114599450120
  pid: 114599450120
  rate: 0.45

jd:
  serverUrl: https://api.jd.com/routerjson
  appKey: fd07e7373553e152016b787fba46c182
  appSecret: eaf58fbf234c406186632d3dcf17771a
  unionId: 2031307306
  positionId: 3100085830
  pid: "2031307306_4100960469_3100085830"
  rate: 0.45

wph:
  pid: "c28e9d647c01577a5355650daf7167d4"
  rate: 0.45

dy:
  rate: 0.40

hjk:
  apiKey: 2ec2ffab04637dfc
  apiUrl: http://api-gw.haojingke.com/index.php/v1/api

hdk:
  apiKey: 59623DEAE2F1
  apiUrl: http://v2.api.haodanku.com
  apiV3Url: http://v3.api.haodanku.com

jtk:
  pubId: 133748
  apiKey: 3GCtAAYc0YuNQNa0hyXxrnu5ZjYkbqIw
  apiUrl: http://api.jutuike.com
  apiActUrl: http://api.act.jutuike.com
